Adding Test Cases for TODOIST/Sections.
api-testing-training-01/rest-api-test-automation pull request #12
Opened 2020-04-13 13:45 UTC by GilmarPozzo

- Create new Section
 - Get all Sections
 - Get Section
 - Update Section // not totally supported
 - Delete Section

2020-04-13 14:00 UTC, GilmarPozzo commented
![report todoist sections](https://user-images.githubusercontent.com/51757211/79126260-9dc40d00-7d6d-11ea-93f2-52e04dbf0143.PNG)

2020-04-16 22:47 UTC, marcos-x86 requested changes

2020-04-16 22:47 UTC, marcos-x86 commented on config.json.dist
> +        "token": "3c79150ab7e966c118b31207525ddf2e71939b32"
Please consider removing your personal token from config.json.dist file.

2020-04-17 13:30 UTC, GilmarPozzo commented on config.json.dist
> +        "token": "3c79150ab7e966c118b31207525ddf2e71939b32"
Done!

2020-04-17 14:21 UTC, marcos-x86 requested changes

2020-04-17 14:21 UTC, marcos-x86 commented on config.json.dist
> +=======
Please consider copying all the content from config.json.dist from develop branch to your branch in order to avoid conflicts.

2020-04-17 15:00 UTC, marcos-x86 commented on config.json.dist
> +=======
Also, please update your branch according to new changes in develop branch.

2020-04-18 13:30 UTC, closed without merging