EP - 1st implementation
api-testing-training-01/rest-api-test-automation pull request #9
Opened 2020-04-08 17:08 UTC by epardo-23

Added features files using the step definitions

2020-04-15 05:09 UTC, epardo23 commented
![image](https://user-images.githubusercontent.com/51796755/79300771-af183100-7eb5-11ea-8844-e7a986f45dee.png)
Allure Report of Pivotal

2020-04-15 05:11 UTC, epardo23 commented
As well I added a new commit with my last changes where I fixed some problems with wrong code implemented before.
Please check it and thanks!

2020-04-16 22:43 UTC, marcos-x86 requested changes

2020-04-16 22:43 UTC, marcos-x86 commented on gradle.properties
> +cucumberOptions=--tags @allPivotalProject
Please consider leaving the content of cucumberOptions in blank.

2020-04-16 22:43 UTC, marcos-x86 commented on config.json.dist
> -{
Please consider not deleting this template file.

2020-04-17 14:14 UTC, marcos-x86 commented
Please update your branch and consider not deleting config.json.dist template file.

2020-04-26 09:51 UTC, epardo-23 commented
I completed trello automated test cases, please check it. Thanks
![image](https://user-images.githubusercontent.com/62032357/80304069-e2926f80-8781-11ea-9086-507ff68baf3a.png)

2020-04-26 18:57 UTC, marcos-x86 approved these changes

2020-04-26 18:59 UTC, merged